name: second_life
description: SecondLife

publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 0.0.1+1

environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # A
  agora_rtc_engine: ^5.3.0

  # B

  # C
  cupertino_icons: ^1.0.5
  cached_network_image: ^3.2.3

  # D
  dio: ^5.2.0+1

  # E
  extended_image: ^8.0.2

  # F
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  flutter_rating_bar: ^4.0.1
  firebase_messaging: ^14.6.2
  flutter_easyloading: ^3.0.5
  flutter_local_notifications: ^14.1.1
  firebase_crashlytics: ^3.3.2
  firebase_storage: ^11.2.2
  fluttertoast: ^8.2.2
  avatar_glow: ^2.0.2

  # G
  google_fonts: ^4.0.3
  get: ^4.6.5

  # H

  # I
  intl_phone_field: ^3.1.0

  # P
  pin_code_fields: ^7.4.0
  permission_handler: ^10.2.1
  percent_indicator: ^4.2.3

  provider: ^6.0.5

  # R
  razorpay_flutter: ^1.3.4

  # S
  shared_preferences: ^2.1.2
  stop_watch_timer: ^2.0.0
  shimmer: ^3.0.0
  share_plus: ^6.3.1

  url_launcher: ^6.1.11


  just_audio: ^0.9.32
  audioplayers: ^3.0.1

  image_picker: ^0.8.7+5
  timeago_flutter: ^3.4.0
  cloud_firestore: ^4.8.0
  # device_info_plus: ^4.0.1
  intl: ^0.18.1
  http: ^0.13.5

  pull_to_refresh: ^2.0.0
  flutter_ringtone_player: ^3.2.0
  flutter_windowmanager: ^0.2.0
  in_app_update: ^4.0.1
  material_design_icons_flutter: ^6.0.7096
  go_router: ^8.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/
    - assets/sound/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
