// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAMoO-t3GaadWslihsrYkOCVi3ihikKBJA',
    appId: '1:1001666049921:web:236289d1af3d072a949a80',
    messagingSenderId: '1001666049921',
    projectId: 'secondlife-98686',
    authDomain: 'SecondLife.in',
    storageBucket: 'secondlife-98686.appspot.com',
    measurementId: 'G-L579D7D7P9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB2nUse9y8IQZwL0HEqLTeM7L_qCJd7TII',
    appId: '1:1001666049921:android:dcf3b4eb64115342949a80',
    messagingSenderId: '1001666049921',
    projectId: 'secondlife-98686',
    storageBucket: 'secondlife-98686.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzpmSFZdHGwW0xWZC6b9NX24QAp1rDJHA',
    appId: '1:1001666049921:ios:8b98def9a3ea3e01949a80',
    messagingSenderId: '1001666049921',
    projectId: 'secondlife-98686',
    storageBucket: 'secondlife-98686.appspot.com',
    iosClientId:
        '1001666049921-5ii6jgiudmkbupeanigd666flvqfd04p.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondlife',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzpmSFZdHGwW0xWZC6b9NX24QAp1rDJHA',
    appId: '1:1001666049921:ios:8b98def9a3ea3e01949a80',
    messagingSenderId: '1001666049921',
    projectId: 'secondlife-98686',
    storageBucket: 'secondlife-98686.appspot.com',
    iosClientId:
        '1001666049921-5ii6jgiudmkbupeanigd666flvqfd04p.apps.googleusercontent.com',
    iosBundleId: 'com.example.secondlife',
  );
}
